### PR TITLE
[#299] Fix missing local.yml

### PR DESCRIPTION
**Pull request by ponchofiesta**

### CODE REVIEW

**Comment by pbroman** [comment]
I'm not quite happy about this. The basic idea ist, that you have your local additions / changes to the default.yml checked in in local.yml. The installation manual now suggests something else: that you create a new local.yml from the default.yml and only keep it on your server. I would find that confusing.

**Comment by pbroman** [comment]
Of course, I wasn't thinking far enough. If you install manually from released jars, you don't have a checked in local.yml. 
Still, this installation manual is to be used also if you build from source. So I suggest you add a line, something like this:
"If you build the code from source, you would want to keep your local settings in the `local.yml` file stored in `kitodo-mediaserver-local/src/main/resources/config/`. If you're installing from the released jar and war files, you may create a `local.yml` file using the `default.yml`in the following manner:"

**Comment by ponchofiesta** [comment]
I've added this:
>If you have [built from source](Install-from-source.md), you can save your configuration parameters in the [local.yml](../kitodo-mediaserver-local/src/main/resources/config/local.yml) from the *local* module too. This way you can keep your configuration in your VCS.

(links are relative and will work in the doc file only)

**Comment by ponchofiesta** [comment]
OK, added it.

**Pull request merged**
