### PR TITLE
[#129] Make collection and hostId searchable in the UI

### PR DESCRIPTION
**Pull request by ponchofiesta**

### CODE REVIEW

**Comment by pbroman** [comment]
Code looks good. The search results are however a bit confusing. If I search for collection:something I get everything, some hits even multiplied (when there are several collections for one record). 
General: a search for title: <title> doesn't return any results when there is a space after the colon. Could you perhaps trim the search query?

**Comment by ponchofiesta** [comment]
Thanks for finding this. The title search works like this: "title: bla" searches for an empty string ("") in title field, which matches every work. And it also searches for "bla" in every field. I can't think of an situation when a user wants to search an empty string so I will change it to ignore white spaces after colon.

And I have to investigate the collection problem.

**Comment by pbroman** [comment]
OK. The results are however still multiplied when a work is in several collections. Could you add a 'distinct' to the search?

**Comment by ponchofiesta** [comment]
Now with distinct and a test for this case.

**Pull request merged**
