### PR TITLE
[#20] UI: add user management

### PR DESCRIPTION
**Pull request by ponchofiesta**

### CODE REVIEW

**Comment by pbroman** [comment]
Code is clean and understandable, Javadoc comments are good. :+1: 
However, there are practically no further information in the issue. It would be nice if you could write some conceptual information of the implementation - what it is supposed to do and how this is solved - in the issue comments. That would make it easier for future developers to understand what it is all about.

**Comment by pbroman** [comment]
Testing locally, I find some functional issues too:
* You may disable all users (including yourself) and logout, and then nobody can login. You should not be able to disable yourself.
* In the users list, it would be nice to see if a user is disabled.
The design is however very nice. :)

**Comment by ponchofiesta** [comment]
I fixed these issues (hopefully).

I changed some other things too:
- Merged _messages.properties_ and _validation.properties_ as it wasn't always clear which one is the right file.
- The delete confirmation dialog is separated to make it reusable. Furthermore it uses the button layout "OK - Cancel" (confirmation action first, dismissive action last -> MS Windows style). And it uses an explicit action text instead of just "OK". Both are intended to be everywhere in the UI.
- Replaced Spring's @Autowired field injection by Setters with @Autowired and Getters.

**Comment by pbroman** [comment]
Sieht sehr gut aus und funktioniert auch gut. :+1:

**Pull request merged**
